import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rawData = JSON.parse(readFileSync(join(__dirname, 'icon-data-raw.json'), 'utf-8'));

const iconNames = Object.keys(rawData).sort();
const categories = [...new Set(Object.values(rawData).map(v => v.category).filter(Boolean))].sort();

mkdirSync(join(__dirname, 'packages', 'core', 'src'), { recursive: true });

const iconNameUnion = iconNames.map(n => "  | '" + n + "'").join('\n');
const categoryUnion = categories.map(c => "  | '" + c + "'").join('\n');

const typesContent = [
  '// Auto-generated by generate.mjs — do not edit manually',
  'export type DooIconikName =',
  iconNameUnion + ';',
  '',
  "export type DooIconikSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';",
  '',
  'export type DooIconikCategory =',
  categoryUnion + ';',
  '',
  'export type DooIconikVariant =',
  "  | 'default'",
  "  | 'glow'",
  "  | 'neon'",
  "  | 'shadow'",
  "  | 'embossed'",
  "  | 'glass'",
  "  | 'outline'",
  "  | 'retro';",
  '',
  'export type DooIconikAnimation =',
  "  | 'spin'",
  "  | 'pulse'",
  "  | 'bounce'",
  "  | 'wiggle'",
  "  | 'shake'",
  "  | 'float'",
  "  | 'heartbeat'",
  "  | 'tada'",
  "  | 'rubber'",
  "  | 'swing'",
  "  | 'jello';",
  '',
].join('\n');

writeFileSync(join(__dirname, 'packages', 'core', 'src', 'types.ts'), typesContent);
console.log('Generated packages/core/src/types.ts with ' + iconNames.length + ' icon names and ' + categories.length + ' categories');

// Generate icon-data.ts
const lines = [
  '// Auto-generated by generate.mjs — do not edit manually',
  '',
  'export interface IconData {',
  '  viewBox: string;',
  '  paths: string[];',
  '  circles?: { cx: number; cy: number; r: number }[];',
  '  lines?: { x1: number; y1: number; x2: number; y2: number }[];',
  '  stroke?: boolean;',
  '}',
  '',
  'export const iconData: Record<string, IconData> = {'
];

for (const name of iconNames) {
  const icon = rawData[name];
  const pathsStr = icon.paths.map(p => '      ' + JSON.stringify(p)).join(',\n');

  lines.push('  ' + JSON.stringify(name) + ': {');
  lines.push('    viewBox: ' + JSON.stringify(icon.viewBox) + ',');
  lines.push('    paths: [');
  lines.push(pathsStr);
  lines.push('    ],');

  if (icon.circles && icon.circles.length > 0) {
    const circlesStr = icon.circles.map(c => '      { cx: ' + c.cx + ', cy: ' + c.cy + ', r: ' + c.r + ' }').join(',\n');
    lines.push('    circles: [');
    lines.push(circlesStr);
    lines.push('    ],');
  }

  if (icon.lines && icon.lines.length > 0) {
    const linesStr = icon.lines.map(l => '      { x1: ' + l.x1 + ', y1: ' + l.y1 + ', x2: ' + l.x2 + ', y2: ' + l.y2 + ' }').join(',\n');
    lines.push('    lines: [');
    lines.push(linesStr);
    lines.push('    ],');
  }

  if (icon.stroke) {
    lines.push('    stroke: true,');
  }

  lines.push('  },');
}

lines.push('};');
lines.push('');

writeFileSync(join(__dirname, 'packages', 'core', 'src', 'icon-data.ts'), lines.join('\n'));
console.log('Generated packages/core/src/icon-data.ts with ' + iconNames.length + ' icons');

// Generate individual icon modules for tree-shaking
const JS_RESERVED_WORDS = new Set([
  'break', 'case', 'catch', 'continue', 'debugger', 'default', 'delete',
  'do', 'else', 'export', 'extends', 'finally', 'for', 'function', 'if',
  'import', 'in', 'instanceof', 'new', 'return', 'super', 'switch',
  'this', 'throw', 'try', 'typeof', 'var', 'void', 'while', 'with',
  'yield', 'let', 'static', 'enum', 'await', 'implements', 'package',
  'protected', 'interface', 'private', 'public', 'class', 'const',
]);

function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function safeVarName(str) {
  const camel = kebabToCamel(str);
  return JS_RESERVED_WORDS.has(camel) ? camel + 'Icon' : camel;
}

const iconsDir = join(__dirname, 'packages', 'core', 'src', 'icons');
mkdirSync(iconsDir, { recursive: true });

const barrelExports = [
  '// Auto-generated by generate.mjs — do not edit manually',
];

for (const name of iconNames) {
  const icon = rawData[name];
  const camelName = safeVarName(name);
  const iconJson = JSON.stringify({
    viewBox: icon.viewBox,
    paths: icon.paths,
    ...(icon.circles && icon.circles.length > 0 ? { circles: icon.circles } : {}),
    ...(icon.lines && icon.lines.length > 0 ? { lines: icon.lines } : {}),
    ...(icon.stroke ? { stroke: true } : {}),
  }, null, 2);

  const moduleContent = [
    '// Auto-generated by generate.mjs — do not edit manually',
    "import type { IconData } from '../icon-data.js';",
    '',
    'export const ' + camelName + ': IconData = ' + iconJson + ';',
    'export default ' + camelName + ';',
    '',
  ].join('\n');

  writeFileSync(join(iconsDir, name + '.ts'), moduleContent);
  barrelExports.push("export { " + camelName + " } from './" + name + ".js';");
}

barrelExports.push('');
writeFileSync(join(iconsDir, 'index.ts'), barrelExports.join('\n'));
console.log('Generated ' + iconNames.length + ' individual icon modules in packages/core/src/icons/');

// ─── Icon complexity audit ────────────────────────────────────────────────
// Doodle icons should stay sparse and hand-drawn. Track outliers so that
// new contributions don't drift towards mini-illustration territory.
//
//   Soft cap (warn): ≤ 6 paths,  ≤ 24 commands, ≤ 450 d-chars
//   Hard cap (fail): ≤ 8 paths,  ≤ 32 commands, ≤ 600 d-chars
//
// Pass STRICT_COMPLEXITY=1 to fail the build on hard-cap violations.
// Pass COMPLEXITY_REPORT=path.json to write a machine-readable report.

const SOFT = { paths: 6, cmds: 24, dlen: 450 };
const HARD = { paths: 8, cmds: 32, dlen: 600 };

const CMD_RE = /[MLCAQHVSTZmlcaqhvstz]/g;

function measureIcon(icon) {
  const paths = icon.paths || [];
  const dlen = paths.reduce((a, p) => a + p.length, 0);
  const cmds = paths.reduce((a, p) => a + (p.match(CMD_RE) || []).length, 0);
  return { paths: paths.length, cmds, dlen };
}

const audit = iconNames.map((name) => {
  const m = measureIcon(rawData[name]);
  const overSoft = m.paths > SOFT.paths || m.cmds > SOFT.cmds || m.dlen > SOFT.dlen;
  const overHard = m.paths > HARD.paths || m.cmds > HARD.cmds || m.dlen > HARD.dlen;
  return { name, category: rawData[name].category || '?', ...m, overSoft, overHard };
});

const totals = audit.reduce(
  (a, r) => ({ paths: a.paths + r.paths, cmds: a.cmds + r.cmds, dlen: a.dlen + r.dlen }),
  { paths: 0, cmds: 0, dlen: 0 },
);
const n = audit.length;
const avg = { paths: totals.paths / n, cmds: totals.cmds / n, dlen: totals.dlen / n };

const softViolations = audit.filter((r) => r.overSoft).sort((a, b) => b.cmds - a.cmds);
const hardViolations = audit.filter((r) => r.overHard);

console.log('');
console.log('── Icon complexity audit ──────────────────────────────');
console.log('  icons:        ' + n);
console.log('  avg paths:    ' + avg.paths.toFixed(2) + '  (soft cap ' + SOFT.paths + ')');
console.log('  avg cmds:     ' + avg.cmds.toFixed(2) + '  (soft cap ' + SOFT.cmds + ')');
console.log('  avg d-chars:  ' + avg.dlen.toFixed(0) + '  (soft cap ' + SOFT.dlen + ')');
console.log('  soft viol:    ' + softViolations.length);
console.log('  hard viol:    ' + hardViolations.length);

if (softViolations.length > 0) {
  console.log('');
  console.log('  Top offenders (soft cap exceeded):');
  console.log('    paths cmds dlen  category        name');
  for (const r of softViolations.slice(0, 25)) {
    const tag = r.overHard ? '!' : ' ';
    console.log(
      '  ' + tag + ' ' +
      String(r.paths).padStart(5) + ' ' +
      String(r.cmds).padStart(4) + ' ' +
      String(r.dlen).padStart(4) + '  ' +
      r.category.padEnd(14) + '  ' +
      r.name,
    );
  }
  if (softViolations.length > 25) {
    console.log('    … ' + (softViolations.length - 25) + ' more');
  }
}
console.log('───────────────────────────────────────────────────────');

if (process.env.COMPLEXITY_REPORT) {
  const reportPath = process.env.COMPLEXITY_REPORT;
  writeFileSync(
    reportPath,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        caps: { soft: SOFT, hard: HARD },
        totals: { count: n, avg },
        softViolations,
        hardViolations,
      },
      null,
      2,
    ),
  );
  console.log('Wrote complexity report → ' + reportPath);
}

if (process.env.STRICT_COMPLEXITY === '1' && hardViolations.length > 0) {
  console.error('');
  console.error('STRICT_COMPLEXITY=1: ' + hardViolations.length + ' icon(s) exceed the hard cap.');
  for (const r of hardViolations) {
    console.error('  ✗ ' + r.name + '  paths=' + r.paths + ' cmds=' + r.cmds + ' dlen=' + r.dlen);
  }
  process.exit(1);
}
