import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rawData = JSON.parse(readFileSync(join(__dirname, 'icon-data-raw.json'), 'utf-8'));

const iconNames = Object.keys(rawData).sort();
const categories = [...new Set(Object.values(rawData).map(v => v.category).filter(Boolean))].sort();

mkdirSync(join(__dirname, 'packages', 'core', 'src'), { recursive: true });

const iconNameUnion = iconNames.map(n => "  | '" + n + "'").join('\n');
const categoryUnion = categories.map(c => "  | '" + c + "'").join('\n');

const typesContent = [
  '// Auto-generated by generate.mjs — do not edit manually',
  'export type DooIconikName =',
  iconNameUnion + ';',
  '',
  "export type DooIconikSize = 'xs' | 'sm' | 'md' | 'lg' | 'xl' | '2xl';",
  '',
  'export type DooIconikCategory =',
  categoryUnion + ';',
  '',
  'export type DooIconikVariant =',
  "  | 'default'",
  "  | 'glow'",
  "  | 'neon'",
  "  | 'shadow'",
  "  | 'embossed'",
  "  | 'glass'",
  "  | 'outline'",
  "  | 'retro';",
  '',
  'export type DooIconikAnimation =',
  "  | 'spin'",
  "  | 'pulse'",
  "  | 'bounce'",
  "  | 'wiggle'",
  "  | 'shake'",
  "  | 'float'",
  "  | 'heartbeat'",
  "  | 'tada'",
  "  | 'rubber'",
  "  | 'swing'",
  "  | 'jello';",
  '',
].join('\n');

writeFileSync(join(__dirname, 'packages', 'core', 'src', 'types.ts'), typesContent);
console.log('Generated packages/core/src/types.ts with ' + iconNames.length + ' icon names and ' + categories.length + ' categories');

// Generate icon-data.ts
const lines = [
  '// Auto-generated by generate.mjs — do not edit manually',
  '',
  'export interface IconData {',
  '  viewBox: string;',
  '  paths: string[];',
  '  circles?: { cx: number; cy: number; r: number }[];',
  '  lines?: { x1: number; y1: number; x2: number; y2: number }[];',
  '  stroke?: boolean;',
  '}',
  '',
  'export const iconData: Record<string, IconData> = {'
];

for (const name of iconNames) {
  const icon = rawData[name];
  const pathsStr = icon.paths.map(p => '      ' + JSON.stringify(p)).join(',\n');

  lines.push('  ' + JSON.stringify(name) + ': {');
  lines.push('    viewBox: ' + JSON.stringify(icon.viewBox) + ',');
  lines.push('    paths: [');
  lines.push(pathsStr);
  lines.push('    ],');

  if (icon.circles && icon.circles.length > 0) {
    const circlesStr = icon.circles.map(c => '      { cx: ' + c.cx + ', cy: ' + c.cy + ', r: ' + c.r + ' }').join(',\n');
    lines.push('    circles: [');
    lines.push(circlesStr);
    lines.push('    ],');
  }

  if (icon.lines && icon.lines.length > 0) {
    const linesStr = icon.lines.map(l => '      { x1: ' + l.x1 + ', y1: ' + l.y1 + ', x2: ' + l.x2 + ', y2: ' + l.y2 + ' }').join(',\n');
    lines.push('    lines: [');
    lines.push(linesStr);
    lines.push('    ],');
  }

  if (icon.stroke) {
    lines.push('    stroke: true,');
  }

  lines.push('  },');
}

lines.push('};');
lines.push('');

writeFileSync(join(__dirname, 'packages', 'core', 'src', 'icon-data.ts'), lines.join('\n'));
console.log('Generated packages/core/src/icon-data.ts with ' + iconNames.length + ' icons');

// Generate individual icon modules for tree-shaking
const JS_RESERVED_WORDS = new Set([
  'break', 'case', 'catch', 'continue', 'debugger', 'default', 'delete',
  'do', 'else', 'export', 'extends', 'finally', 'for', 'function', 'if',
  'import', 'in', 'instanceof', 'new', 'return', 'super', 'switch',
  'this', 'throw', 'try', 'typeof', 'var', 'void', 'while', 'with',
  'yield', 'let', 'static', 'enum', 'await', 'implements', 'package',
  'protected', 'interface', 'private', 'public', 'class', 'const',
]);

function kebabToCamel(str) {
  return str.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function safeVarName(str) {
  const camel = kebabToCamel(str);
  return JS_RESERVED_WORDS.has(camel) ? camel + 'Icon' : camel;
}

const iconsDir = join(__dirname, 'packages', 'core', 'src', 'icons');
mkdirSync(iconsDir, { recursive: true });

const barrelExports = [
  '// Auto-generated by generate.mjs — do not edit manually',
];

for (const name of iconNames) {
  const icon = rawData[name];
  const camelName = safeVarName(name);
  const iconJson = JSON.stringify({
    viewBox: icon.viewBox,
    paths: icon.paths,
    ...(icon.circles && icon.circles.length > 0 ? { circles: icon.circles } : {}),
    ...(icon.lines && icon.lines.length > 0 ? { lines: icon.lines } : {}),
    ...(icon.stroke ? { stroke: true } : {}),
  }, null, 2);

  const moduleContent = [
    '// Auto-generated by generate.mjs — do not edit manually',
    "import type { IconData } from '../icon-data.js';",
    '',
    'export const ' + camelName + ': IconData = ' + iconJson + ';',
    'export default ' + camelName + ';',
    '',
  ].join('\n');

  writeFileSync(join(iconsDir, name + '.ts'), moduleContent);
  barrelExports.push("export { " + camelName + " } from './" + name + ".js';");
}

barrelExports.push('');
writeFileSync(join(iconsDir, 'index.ts'), barrelExports.join('\n'));
console.log('Generated ' + iconNames.length + ' individual icon modules in packages/core/src/icons/');
